export const product_reponse = {
  status: 200,
  resultCode: null,
  message: "Success",
  data: [
    {
      id: 13,
      name: "Laptop Dell XPS 15 ",
      imageURL: [
        "https://ecommercespringbootneo4j.s3.ap-southeast-2.amazonaws.com/product/13/image_18218836234318390593360_F_325735908_TkxHU7okor9CTWHBhkGfdRumONWfIDEb.jpg",
        "https://ecommercespringbootneo4j.s3.ap-southeast-2.amazonaws.com/product/13/image_11339590318549373320360_F_627657216_Z3lwjvz1ERj822QFcPXYfrsBraJ7F4mJ.jpg",
      ],
      description:
        "Laptop Dell XPS 15 9520 mang đến hiệu suất mạnh mẽ, màn hình OLED sống động và một thiết kế đẳng cấp. Do đó, Dell XPS 15 9520 hứa hẹn sẽ là chiếc laptop sẵn sàng xử lý mọi công việc bạn muốn ngay lập tức. ",
      oldPrice: 150000,
      price: 100000,
      rating: 4,
      viewCount: 1,
      quantitySold: 0,
      remainingQuantity: 0,
      brandName: null,
      categories: [
        {
          id: 6,
          name: "Jewelry",
          parentID: null,
          noOfViews: 0,
          productsSold: 0,
        },
      ],
    },
    {
      id: 15,
      name: "Laptop Dell XPS 15 ",
      imageURL: null,
      description:
        "Laptop Dell XPS 15 9520 mang đến hiệu suất mạnh mẽ, màn hình OLED sống động và một thiết kế đẳng cấp. Do đó, Dell XPS 15 9520 hứa hẹn sẽ là chiếc laptop sẵn sàng xử lý mọi công việc bạn muốn ngay lập tức. ",
      oldPrice: 150000,
      price: 100000,
      rating: 4,
      viewCount: 0,
      quantitySold: 0,
      remainingQuantity: 0,
      brandName: null,
      categories: [
        {
          id: 4,
          name: "Electronics",
          parentID: null,
          noOfViews: 0,
          productsSold: 0,
        },
      ],
    },
    {
      id: 16,
      name: "Laptop Dell XPS 15 ",
      imageURL: null,
      description:
        "Laptop Dell XPS 15 9520 mang đến hiệu suất mạnh mẽ, màn hình OLED sống động và một thiết kế đẳng cấp. Do đó, Dell XPS 15 9520 hứa hẹn sẽ là chiếc laptop sẵn sàng xử lý mọi công việc bạn muốn ngay lập tức. ",
      oldPrice: 150000,
      price: 100000,
      rating: 4,
      viewCount: 7,
      quantitySold: 6,
      remainingQuantity: 94,
      brandName: null,
      categories: [
        {
          id: 4,
          name: "Electronics",
          parentID: null,
          noOfViews: 0,
          productsSold: 0,
        },
        {
          id: 6,
          name: "Jewelry",
          parentID: null,
          noOfViews: 0,
          productsSold: 0,
        },
        {
          id: 7,
          name: "Toys",
          parentID: null,
          noOfViews: 0,
          productsSold: 0,
        },
      ],
    },
    {
      id: 20,
      name: "Laptop Dell XPS 15 ",
      imageURL: null,
      description:
        "Laptop Dell XPS 15 9520 mang đến hiệu suất mạnh mẽ, màn hình OLED sống động và một thiết kế đẳng cấp. Do đó, Dell XPS 15 9520 hứa hẹn sẽ là chiếc laptop sẵn sàng xử lý mọi công việc bạn muốn ngay lập tức. ",
      oldPrice: 150000,
      price: 100000,
      rating: 4,
      viewCount: 0,
      quantitySold: 0,
      remainingQuantity: 0,
      brandName: null,
      categories: [
        {
          id: 7,
          name: "Toys",
          parentID: null,
          noOfViews: 0,
          productsSold: 0,
        },
      ],
    },
    {
      id: 21,
      name: "Laptop Dell XPS 15 ",
      imageURL: null,
      description:
        "Laptop Dell XPS 15 9520 mang đến hiệu suất mạnh mẽ, màn hình OLED sống động và một thiết kế đẳng cấp. Do đó, Dell XPS 15 9520 hứa hẹn sẽ là chiếc laptop sẵn sàng xử lý mọi công việc bạn muốn ngay lập tức. ",
      oldPrice: 150000,
      price: 100000,
      rating: 4,
      viewCount: 0,
      quantitySold: 0,
      remainingQuantity: 0,
      brandName: null,
      categories: [
        {
          id: 7,
          name: "Toys",
          parentID: null,
          noOfViews: 0,
          productsSold: 0,
        },
      ],
    },
    {
      id: 22,
      name: "Laptop Dell XPS 15 ",
      imageURL: null,
      description:
        "Laptop Dell XPS 15 9520 mang đến hiệu suất mạnh mẽ, màn hình OLED sống động và một thiết kế đẳng cấp. Do đó, Dell XPS 15 9520 hứa hẹn sẽ là chiếc laptop sẵn sàng xử lý mọi công việc bạn muốn ngay lập tức. ",
      oldPrice: 150000,
      price: 100000,
      rating: 4,
      viewCount: 0,
      quantitySold: 0,
      remainingQuantity: 0,
      brandName: null,
      categories: [
        {
          id: 7,
          name: "Toys",
          parentID: null,
          noOfViews: 0,
          productsSold: 0,
        },
      ],
    },
    {
      id: 23,
      name: "Laptop Dell XPS 15 ",
      imageURL: null,
      description:
        "Laptop Dell XPS 15 9520 mang đến hiệu suất mạnh mẽ, màn hình OLED sống động và một thiết kế đẳng cấp. Do đó, Dell XPS 15 9520 hứa hẹn sẽ là chiếc laptop sẵn sàng xử lý mọi công việc bạn muốn ngay lập tức. ",
      oldPrice: 150000,
      price: 100000,
      rating: 4,
      viewCount: 1,
      quantitySold: 0,
      remainingQuantity: 0,
      brandName: null,
      categories: [
        {
          id: 7,
          name: "Toys",
          parentID: null,
          noOfViews: 0,
          productsSold: 0,
        },
      ],
    },
  ],
};
