export const fake_data_categorys = [
  {
    id: 2,
    name: "Electronic",
    parentID: null,
    createdAt: null,
    updatedAt: null,
    subCategory: [
      {
        id: 55,
        name: "Laptop",
        parentID: null,
        createdAt: "2024-09-03T16:27:54.491758854",
        updatedAt: null,
        subCategory: [],
        noOfViews: 0,
        productsSold: 0,
      },
      {
        id: 44,
        name: "Smart Phone",
        parentID: null,
        createdAt: "2024-09-03T16:15:23.149005144",
        updatedAt: null,
        subCategory: [],
        noOfViews: 0,
        productsSold: 0,
      },
    ],
    noOfViews: 0,
    productsSold: 0,
  },
  {
    id: 44,
    name: "Smart Phone",
    parentID: null,
    createdAt: "2024-09-03T16:15:23.149005144",
    updatedAt: null,
    subCategory: [],
    noOfViews: 0,
    productsSold: 0,
  },
  {
    id: 3,
    name: "Book",
    parentID: null,
    createdAt: null,
    updatedAt: null,
    subCategory: [],
    noOfViews: 0,
    productsSold: 0,
  },
  {
    id: 4,
    name: "Jewelry ",
    parentID: null,
    createdAt: null,
    updatedAt: null,
    subCategory: [],
    noOfViews: 0,
    productsSold: 0,
  },
  {
    id: 5,
    name: "Sports",
    parentID: null,
    createdAt: null,
    updatedAt: null,
    subCategory: [],
    noOfViews: 0,
    productsSold: 0,
  },
  {
    id: 6,
    name: "Watches",
    parentID: null,
    createdAt: null,
    updatedAt: null,
    subCategory: [],
    noOfViews: 0,
    productsSold: 0,
  },
  {
    id: 7,
    name: "Game",
    parentID: null,
    createdAt: null,
    updatedAt: null,
    subCategory: [],
    noOfViews: 0,
    productsSold: 0,
  },
  {
    id: 8,
    name: "Fine Arts",
    parentID: null,
    createdAt: null,
    updatedAt: null,
    subCategory: [],
    noOfViews: 0,
    productsSold: 0,
  },
  {
    id: 9,
    name: "Software",
    parentID: null,
    createdAt: null,
    updatedAt: null,
    subCategory: [],
    noOfViews: 0,
    productsSold: 0,
  },
  {
    id: 10,
    name: "Furniture",
    parentID: null,
    createdAt: null,
    updatedAt: null,
    subCategory: [],
    noOfViews: 0,
    productsSold: 0,
  },

  {
    id: 55,
    name: "Laptop",
    parentID: null,
    createdAt: "2024-09-03T16:27:54.491758854",
    updatedAt: null,
    subCategory: [],
    noOfViews: 0,
    productsSold: 0,
  },
];
