export const productDetailsData = {
  id: 1001,
  name: "Samsung Galaxy Z Fold6",
  brand: "Samsung",
  description:
    "Experience the future of smartphones with the Samsung Galaxy Z Fold6. This innovative device combines a foldable display with cutting-edge technology, offering a tablet-like experience in a pocket-sized form factor.",
  inventory: {
    quantity: 500,
    sku: "SGF6-2024",
  },
  variants: {
    color: ["blue", "black", "white"],
    ram: ["16", "32", "64"],
    storage: ["16", "32"],
  },
  shipping: {
    weight: 275,
    dimensions: {
      length: 158.2,
      width: 128.1,
      height: 6.9,
    },
  },
  sellingType: "Available both online and in-store",
  features: [
    "7.6-inch Dynamic AMOLED 2X main display",
    "6.2-inch Super AMOLED cover display",
    "5G connectivity",
    "Triple rear camera system",
    "5000mAh battery with fast charging",
    "IPX8 water resistance",
  ],
  images: [
    {
      variant_type: "color",
      value: "white",
      variant_images: [
        "https://cdn2.cellphones.com.vn/insecure/rs:fill:358:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/s/a/samsung-galaxy-z-fold-6-xanh_5_.png",
        "https://cdn2.cellphones.com.vn/insecure/rs:fill:0:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/s/a/samsung_galaxy_z_fold_6_-_1_2.png",
      ],
    },
    {
      variant_type: "color",
      value: " blue",
      variant_images: [
          "https://cdn2.cellphones.com.vn/x/media/catalog/product/s/a/samsung_galaxy_z_fold_6_-_2_2.png",
          "https://cdn2.cellphones.com.vn/x/media/catalog/product/s/a/samsung_galaxy_z_fold_6_-_3_2.png",
      ],
    },
    {
      variant_type: "color",
      value: "black",
      variant_images: [
        "https://cdn2.cellphones.com.vn/insecure/rs:fill:0:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/m/a/macbook-pro-14-inch-m3-2023_2_.png",
        "https://cdn2.cellphones.com.vn/x/media/catalog/product/m/a/macbook-pro-14-inch-m3-2023_3_.png",
      ],
    },
  ],
  category: [
    {
      id: 2,
      name: "Computers",
      parentID: null,
      createdAt: "2023-02-01T08:00:00Z",
      updatedAt: "2024-02-01T08:00:00Z",
      subCategory: [],
      noOfViews: 5000,
      ListSold: 500,
    },
    {
      id: 44,
      name: "Smart phone",
      parentID: null,
      createdAt: "2023-02-01T08:00:00Z",
      updatedAt: "2024-02-01T08:00:00Z",
      subCategory: [],
      noOfViews: 5000,
      ListSold: 500,
    },
  ],
  variantOption: [
    {
      color: "blue",
      ram: "16 gb",
      storage: "16 ssd",
      price: 1050,
      msrp: 950,
      sale: 1100,
    },
    {
      color: "blue",
      ram: "16 gb",
      storage: "32 ssd",
      price: 1150,
      msrp: 960,
      sale: 1020,
    },
    {
      color: "blue",
      ram: "32 gb",
      storage: "16 ssd",
      price: 1200,
      msrp: 990,
      sale: 1080,
    },
    {
      color: "blue",
      ram: "32 gb",
      storage: "32 ssd",
      price: 1220,
      msrp: 980,
      sale: 1110,
    },
    {
      color: "blue",
      ram: "64 gb",
      storage: "16 ssd",
      price: 1300,
      msrp: 1000,
      sale: 1150,
    },
    {
      color: "blue",
      ram: "64 gb",
      storage: "32 ssd",
      price: 1350,
      msrp: 1020,
      sale: 1200,
    },
    {
      color: "black",
      ram: "16 gb",
      storage: "16 ssd",
      price: 1070,
      msrp: 950,
      sale: 1100,
    },
    {
      color: "black",
      ram: "16 gb",
      storage: "32 ssd",
      price: 1170,
      msrp: 960,
      sale: 1020,
    },
    {
      color: "black",
      ram: "32 gb",
      storage: "16 ssd",
      price: 1210,
      msrp: 990,
      sale: 1080,
    },
    {
      color: "black",
      ram: "32 gb",
      storage: "32 ssd",
      price: 1230,
      msrp: 980,
      sale: 1110,
    },
    {
      color: "black",
      ram: "64 gb",
      storage: "16 ssd",
      price: 1320,
      msrp: 1000,
      sale: 1150,
    },
    {
      color: "black",
      ram: "64 gb",
      storage: "32 ssd",
      price: 1370,
      msrp: 1020,
      sale: 1200,
    },
    {
      color: "blue",
      ram: "16 gb",
      storage: "16 ssd",
      price: 1090,
      msrp: 950,
      sale: 1100,
    },
    {
      color: "blue",
      ram: "16 gb",
      storage: "32 ssd",
      price: 1190,
      msrp: 960,
      sale: 1020,
    },
    {
      color: "blue",
      ram: "32 gb",
      storage: "16 ssd",
      price: 1240,
      msrp: 990,
      sale: 1080,
    },
    {
      color: "blue",
      ram: "32 gb",
      storage: "32 ssd",
      price: 1260,
      msrp: 980,
      sale: 1110,
    },
    {
      color: "blue",
      ram: "64 gb",
      storage: "16 ssd",
      price: 1340,
      msrp: 1000,
      sale: 1150,
    },
    {
      color: "blue",
      ram: "64 gb",
      storage: "32 ssd",
      price: 1390,
      msrp: 1020,
      sale: 1200,
    },
  ],
};
